# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name:   "%kernel.root_dir%/migrations"
    namespace:  Acme\Migrations
    table_name: app_migrations
    name:       "Doctrine Migrations"
